FROM caddy:2.10

RUN addgroup -S smgroup && \
    adduser -S smuser -G smgroup

RUN mkdir -p /config /data && \
    chown -R smuser:smgroup /config /data

COPY --chown=smuser:smgroup /docker/dist/ /app
COPY --chown=smuser:smgroup /docker/Caddyfile /etc/caddy/Caddyfile

LABEL maintainer="Miłosz Gilga <miloszgilga@gmail.com>"

EXPOSE 8080

USER smuser
